### ISSUE TITLE
Error message using the Connect-MgGraph when I click on Connect

### ISSUE THREAD

**Issue by amagre** [rafallz10100/AutopilotV2BulkImport#1]
I get an error the moment click on "Connect"..

"Attempting to connect to graph...
The term 'Connect-MgGraph' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."

Any ideas?

Thanks
Amag

**Comment by rafallz10100** [comment]
in the application requirements it says that the Microsoft.Graph.Authentication powershell module is needed.

Run powershell and install the required module:
Install-Module -Name "Microsoft.Graph.Authentication" -Force

**Comment by amagre** [comment]
Thanks for resolving the previous issue. When authenticating through MFA it tells me it "Need admin approval". So it requires permissions to access resources in our tenant. Can you provide the details of what permissions or access it requires? I can then run this by our internal Cyber team for approval. 

Thanks,
Amag

**Comment by rafallz10100** [comment]
I encourage you to review the code.

Required permissions:
DeviceManagementServiceConfig.ReadWrite.All, DeviceManagementManagedDevices.Read.All
